mkdir -p $HOME/go/src/github.com/foxbroadcasting/
mkdir -p $HOME/Projects/Personales/

REPOS="$HOME/.dotfiles?git@github.com:alexishevia/.dotfiles.git
$HOME/knowledge-base?git@github.com:alexishevia/knowledge-base.git
$HOME/Projects/Personales/mdo?git@github.com:mdo-org/mdo.git
$HOME/Projects/Personales/mdo-native?git@github.com:mdo-org/mdo-native.git
$HOME/Projects/Personales/personal_finance?git@bitbucket.org:alexishevia/personal_finance.git
$HOME/Projects/Personales/zettelkasten?git@github.com:alexishevia/zettelkasten.git
$HOME/Projects/Personales/izinput?git@github.com:alexishevia/izinput.git
$HOME/Projects/Personales/izinput-pwa?git@github.com:alexishevia/izinput-pwa.git
$HOME/Projects/Personales/izreducer?git@github.com:alexishevia/izreducer.git
$HOME/Projects/Personales/redux-file-sync?git@github.com:alexishevia/redux-file-sync.git
$HOME/Projects/Personales/invoice-zero?git@github.com:alexishevia/invoice-zero.git
$HOME/Projects/Personales/naratrujillo.com?git@bitbucket.org:alexishevia/naratrujillo.com.git
$HOME/Projects/FOX/cpe-node-services?git@github.com:foxbroadcasting/cpe-node-services.git
$HOME/Projects/FOX/video-livestream-test-harness?git@github.com:foxbroadcasting/video-livestream-test-harness
$HOME/Projects/FOX/apigateway?git@github.com:foxbroadcasting/apigateway.git
$HOME/Projects/FOX/cpe-lp-url?git@github.com:foxbroadcasting/cpe-lp-url
$HOME/Projects/FOX/cpe-liveplayer?git@github.com:foxbroadcasting/cpe-liveplayer.git
$HOME/Projects/FOX/cpe-psu?git@github.com:foxbroadcasting/cpe-psu
$HOME/Projects/FOX/cpe-video-service?git@github.com:foxbroadcasting/cpe-video-service.git
$HOME/Projects/FOX/cpe-canIplay?git@github.com:foxbroadcasting/cpe-canIplay
$HOME/Projects/FOX/cpe-watch?git@github.com:foxbroadcasting/cpe-watch.git
$HOME/Projects/FOX/cpe-header-bidding?git@github.com:foxbroadcasting/cpe-header-bidding.git
$HOME/Projects/FOX/cpe-epglistings?git@github.com:foxbroadcasting/cpe-epglistings.git
$HOME/Projects/FOX/cpe-contentsku?git@github.com:foxbroadcasting/cpe-contentsku
$HOME/Projects/FOX/cpe-geo-service?git@github.com:foxbroadcasting/cpe-geo-service
$HOME/Projects/FOX/cpe-screens?git@github.com:foxbroadcasting/cpe-screens
$HOME/Projects/FOX/cpe-screenpanels?git@github.com:foxbroadcasting/cpe-screenpanels
$HOME/Projects/FOX/cpe-asset-info?git@github.com:foxbroadcasting/cpe-asset-info
$HOME/go/src/github.com/foxbroadcasting/cpe-lp-listings?git@github.com:foxbroadcasting/cpe-lp-listings
$HOME/go/src/github.com/foxbroadcasting/cpe-lp-videos?git@github.com:foxbroadcasting/cpe-lp-videos
$HOME/go/src/github.com/foxbroadcasting/cpe-lp-listings-shows?git@github.com:foxbroadcasting/cpe-lp-listings-shows
$HOME/go/src/github.com/foxbroadcasting/cpe-mediasources?git@github.com:foxbroadcasting/cpe-mediasources
$HOME/go/src/github.com/foxbroadcasting/cpe-lpsu?git@github.com:foxbroadcasting/cpe-lpsu
$HOME/go/src/github.com/foxbroadcasting/cpe-station-locator?git@github.com:foxbroadcasting/cpe-station-locator
$HOME/go/src/github.com/foxbroadcasting/cpe-dma?git@github.com:foxbroadcasting/cpe-dma
$HOME/go/src/github.com/foxbroadcasting/cpe-listings?git@github.com:foxbroadcasting/cpe-listings
$HOME/go/src/github.com/foxbroadcasting/cpe-assetvideo?git@github.com:foxbroadcasting/cpe-assetvideo
$HOME/go/src/github.com/foxbroadcasting/cpe-assetimage?git@github.com:foxbroadcasting/cpe-assetimage
$HOME/go/src/github.com/foxbroadcasting/cpe-foxentitlement?git@github.com:foxbroadcasting/cpe-foxentitlement.git
$HOME/go/src/github.com/foxbroadcasting/cpe-cli?git@github.com:foxbroadcasting/cpe-cli.git
$HOME/go/src/github.com/foxbroadcasting/cpe-sportsplayer?git@github.com:foxbroadcasting/cpe-sportsplayer.git
$HOME/go/src/github.com/foxbroadcasting/tracking-data-helper?git@github.com:foxbroadcasting/tracking-data-helper.git
$HOME/go/src/github.com/foxbroadcasting/go-helpers?git@github.com:foxbroadcasting/go-helpers.git
$HOME/go/src/github.com/foxbroadcasting/dcg-gomodels?git@github.com:foxbroadcasting/dcg-gomodels.git"
