#!/bin/bash

# if 'fox' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - tail: docker-compose up
# - test: bin/unit-test

tmux has-session -t fox

if [ $? != 0 ]
then
    # editor window
    tmux new -s fox -n editor -d
    tmux send-keys -t fox:editor 'cd $HOME/Projects/FOX/cpe-node-services' C-m
    tmux send-keys -t fox:editor 'nvm use' C-m
    tmux send-keys -t fox:editor 'source ../.aws_keys' C-m
    tmux send-keys -t fox:editor 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:editor 'clear' C-m
    tmux send-keys -t fox:editor 'git pull' C-m
    tmux send-keys -t fox:editor 'vim .'

    # tail window
    tmux new-window -t fox -n tail
    tmux send-keys -t fox:tail 'cd $HOME/Projects/FOX/cpe-node-services' C-m
    tmux send-keys -t fox:tail 'nvm use' C-m
    tmux send-keys -t fox:tail 'source ../.aws_keys' C-m
    tmux send-keys -t fox:tail 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:tail 'clear' C-m
    tmux send-keys -t fox:tail 'ln -sf ./env/d2c/vpn.env .env' C-m
    tmux send-keys -t fox:tail 'bin/setup && bin/build && docker-compose up -d video liveplayer vodplayer && docker-compose logs -f | grep -v health | grep -v nsolid'

    # test window
    tmux new-window -t fox -n test
    tmux send-keys -t fox:test 'cd $HOME/Projects/FOX/cpe-node-services' C-m
    tmux send-keys -t fox:test 'nvm use' C-m
    tmux send-keys -t fox:test 'source ../.aws_keys' C-m
    tmux send-keys -t fox:test 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:test 'ctags -R .' C-m
    tmux send-keys -t fox:test 'clear' C-m
    tmux send-keys -t fox:test 'bin/unit-test -p service-video-d2c -P'
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux attach -t fox
else
    tmux switch -t fox
fi

# select 'tail' window
tmux select-window -t fox:tail
