#!/bin/bash

# if 'cpe-node-services' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: nvim
# - run: node

tmux has-session -t cpe-node-services

if [ $? != 0 ]
then
    # editor window
    tmux new -s cpe-node-services -n editor -d
    tmux send-keys -t cpe-node-services:editor 'cd $HOME/Projects/FOX/cpe-node-services' C-m
    tmux send-keys -t cpe-node-services:editor 'nvm use' C-m
    tmux send-keys -t cpe-node-services:editor 'source $HOME/Dropbox/.aws_keys' C-m
    tmux send-keys -t cpe-node-services:editor 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t cpe-node-services:editor 'clear' C-m
    tmux send-keys -t cpe-node-services:editor 'git pull' C-m
    tmux send-keys -t cpe-node-services:editor 'nvim .'

    # run window
    tmux new-window -t cpe-node-services -n run
    tmux send-keys -t cpe-node-services:run 'cd $HOME/Projects/FOX/cpe-node-services' C-m
    tmux send-keys -t cpe-node-services:run 'nvm use' C-m
    tmux send-keys -t cpe-node-services:run 'source $HOME/Dropbox/.aws_keys' C-m
    tmux send-keys -t cpe-node-services:run 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t cpe-node-services:run 'clear' C-m
    tmux send-keys -t cpe-node-services:run 'docker-compose up -d video geo screens categories && docker-compose logs -f'
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux select-window -t cpe-node-services:editor
    tmux attach -t cpe-node-services
else
    tmux switch -t cpe-node-services
fi
