#!/bin/bash

# if '_todo' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: open work.md and home.md
#   - gofox: connect to foxvpn + ssh to cpe-dev-fwd

set -- $(stty size) # $1 = rows $2 = columns

tmux has-session -t _todo

if [ $? != 0 ]
then
    # editor window
    tmux new -s _todo -n editor -d -x "$2" -y "$(($1 - 1))" # https://superuser.com/questions/354844/cannot-resize-tmux-pane-from-bash-script
    tmux send-keys -t _todo:editor 'cd ~/Dropbox' C-m
    tmux send-keys -t _todo:editor 'vim ~/Dropbox/working-on.md' C-m

    tmux split-window -t _todo:editor -p 88

    tmux send-keys -t _todo:editor.0 ':AirlineToggle' C-m
    tmux send-keys -t _todo:editor.0 ':set noshowmode' C-m
    tmux send-keys -t _todo:editor.0 ':set noruler' C-m
    tmux send-keys -t _todo:editor.0 ':set laststatus=0' C-m
    tmux send-keys -t _todo:editor.0 ':set noshowcmd' C-m
    tmux send-keys -t _todo:editor.0 ':set shortmess=F' C-m

    tmux send-keys -t _todo:editor.1 'cd ~/Dropbox' C-m
    tmux send-keys -t _todo:editor.1 'vim .' C-m
    tmux send-keys -t _todo:editor.1 ',t' C-m
    tmux send-keys -t _todo:editor.1 ':edit ~/Dropbox/todo/work.md' C-m
    tmux send-keys -t _todo:editor.1 ',t' C-m
    tmux send-keys -t _todo:editor.1 ':edit ~/Dropbox/todo/home.md' C-m
    tmux send-keys -t _todo:editor.1 ',t' C-m
    tmux send-keys -t _todo:editor.1 ':edit ~/Dropbox/todo/bounties.md' C-m

    # gofox window
    top=$(tmux new-window -t _todo -n gofox -P -F "#{pane_id}")
    bottom=$(tmux split-window -t _todo:gofox.$top -P -F "#{pane_id}" -p 75)

    tmux send-keys -t _todo:gofox.$top 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t _todo:gofox.$top 'foxvpn'

    tmux send-keys -t _todo:gofox.$bottom 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t _todo:gofox.$bottom 'okta-awscli --okta-profile dcg_dev --profile dcg_dev && ssh cpe-dev-fwd -N'
fi

# select 'editor' window
tmux select-window -t _todo:editor
tmux select-pane -t _todo:editor.0

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t _todo
else
    tmux attach -t _todo
fi
