#!/bin/bash

# opens a golang repo in a new tmux session
repo=$1

if [ -z "$repo" ]
then
  echo "You must provide a repo name as the first argument"
  exit 1
fi

fullpath="$HOME/Projects/FOX/$repo"
if [ ! -d $fullpath ]
then
  echo "Directory does not exist: $fullpath"
  exit 1
fi

# if there is no existing tmux session for this repo, create it with the
# following windows:
# - editor: nvim
# - run: dlv debug
tmux has-session -t $repo
if [ $? != 0 ]
then
  # editor window
  tmux new -s $repo -n editor -d
  tmux send-keys -t $repo:editor "cd $fullpath" C-m
  tmux send-keys -t $repo:editor 'nvim .' C-m

  # debug window
  tmux new-window -t $repo -n debug
  tmux send-keys -t $repo:debug "cd $fullpath" C-m
  tmux send-keys -t $repo:debug 'export USE_LOCAL_APIKEYS=$HOME/Dropbox/FOX/apikeys.json && export USE_LOCAL_PLATFORMS=$HOME/Dropbox/FOX/platforms.json && dlv debug .'
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux select-window -t $repo:editor
    tmux attach -t $repo
else
    tmux switch -t $repo
fi
