#!/bin/bash

# if 'contentsku' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - make/test: make run-local + go test

tmux has-session -t contentsku

if [ $? != 0 ]
then
    # editor window
    tmux new -s contentsku -n editor -d
    tmux send-keys -t contentsku:editor 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-contentsku' C-m
    tmux send-keys -t contentsku:editor 'git pull' C-m
    tmux send-keys -t contentsku:editor 'vim .'

    # make/test window
    tmux new-window -t contentsku -n make/test
    tmux send-keys -t contentsku:make/test 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-contentsku' C-m
    tmux send-keys -t contentsku:make/test 'glide install' C-m
    tmux send-keys -t contentsku:make/test 'export AWS_PROFILE=cpe-dev1 && USE_LOCAL_APIKEYS=~/Downloads/apikeys.json onchange -i -k "**/*.go" -- make run-local'
    tmux split-window -t contentsku:make/test
    tmux send-keys -t contentsku:make/test.1 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-contentsku' C-m
    tmux send-keys -t contentsku:make/test.1 'go test ./...'
fi

# select 'editor' pane
tmux select-pane -t contentsku:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t contentsku
else
    tmux attach -t contentsku
fi
