#!/bin/bash

# if 'assetimage' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - make/test: make run-local + go test
# - ssh/swagger: ssh to cpe-dev-fwd + swagger-editor

tmux has-session -t assetimage

if [ $? != 0 ]
then
    # editor window
    tmux new -s assetimage -n editor -d
    tmux send-keys -t assetimage:editor 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-assetimage' C-m
    tmux send-keys -t assetimage:editor 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t assetimage:editor 'git pull' C-m
    tmux send-keys -t assetimage:editor 'vim .'

    # make/test window
    top=$(tmux new-window -t assetimage -n make/test -P -F "#{pane_id}")
    bottom=$(tmux split-window -t assetimage:make/test -P -F "#{pane_id}")
    tmux send-keys -t assetimage:make/test.$top 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-assetimage' C-m
    tmux send-keys -t assetimage:make/test.$top 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t assetimage:make/test.$top 'glide install' C-m
    tmux send-keys -t assetimage:make/test.$top 'export AWS_PROFILE=dcg_dev && USE_LOCAL_APIKEYS=~/Downloads/apikeys.json onchange -i -k "**/*.go" -- make run-local'
    tmux send-keys -t assetimage:make/test.$bottom 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-assetimage' C-m
    tmux send-keys -t assetimage:make/test.$bottom 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t assetimage:make/test.$bottom 'go test ./...'
fi

# select 'editor' pane
tmux select-pane -t assetimage:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t assetimage
else
    tmux attach -t assetimage
fi
