#!/bin/bash

# if 'station-locator' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - make/test: make run-local + go test

tmux has-session -t station-locator

if [ $? != 0 ]
then
    # editor window
    tmux new -s station-locator -n editor -d
    tmux send-keys -t station-locator:editor 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-station-locator' C-m
    tmux send-keys -t station-locator:editor 'git pull' C-m
    tmux send-keys -t station-locator:editor 'vim .'

    # make/test window
    tmux new-window -t station-locator -n make/test
    tmux send-keys -t station-locator:make/test 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-station-locator' C-m
    tmux send-keys -t station-locator:make/test 'glide install' C-m
    tmux send-keys -t station-locator:make/test 'onchange -i -k "**/*.go" -- make run-local'
    tmux split-window -t station-locator:make/test
    tmux send-keys -t station-locator:make/test.1 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-station-locator' C-m
    tmux send-keys -t station-locator:make/test.1 'go test ./...'
fi

# select 'editor' pane
tmux select-pane -t station-locator:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t station-locator
else
    tmux attach -t station-locator
fi
