#!/bin/bash

# if 'knowledge' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: nvim
#   - docsify: docsify serve

tmux has-session -t knowledge

if [ $? != 0 ]
then
    # editor window
    tmux new -s knowledge -n editor -d
    tmux send-keys -t knowledge:editor 'cd ~/knowledge-base' C-m
    tmux send-keys -t knowledge:editor 'nvim .' C-m

    # docsify window
    tmux new-window -t knowledge -n docsify
    tmux send-keys -t knowledge:docsify 'cd ~/knowledge-base' C-m
    tmux send-keys -t knowledge:docsify 'docsify serve .' C-m
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux attach -t knowledge
else
    tmux switch -t knowledge
fi

# select window 'editor'
tmux select-window -t knowledge:editor
