#!/bin/bash

# if '_todo' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: open work.md and home.md

set -- $(stty size) # $1 = rows $2 = columns

tmux has-session -t _todo

if [ $? != 0 ]
then
    # editor window
    tmux new -s _todo -n editor -d -x "$2" -y "$(($1 - 1))" # https://superuser.com/questions/354844/cannot-resize-tmux-pane-from-bash-script

    tmux send-keys -t _todo:editor 'dropbox start' C-m # make sure dropbox is running

    tmux send-keys -t _todo:editor 'cd ~/Dropbox' C-m
    tmux send-keys -t _todo:editor 'nvim ~/Dropbox/working-on.md' C-m

    tmux split-window -t _todo:editor -p 88

    tmux send-keys -t _todo:editor.0 ':AirlineToggle' C-m
    tmux send-keys -t _todo:editor.0 ':set noshowmode' C-m
    tmux send-keys -t _todo:editor.0 ':set noruler' C-m
    tmux send-keys -t _todo:editor.0 ':set laststatus=0' C-m
    tmux send-keys -t _todo:editor.0 ':set noshowcmd' C-m
    tmux send-keys -t _todo:editor.0 ':set shortmess=F' C-m

    tmux send-keys -t _todo:editor.1 'cd ~/Dropbox' C-m
    tmux send-keys -t _todo:editor.1 'nvim .' C-m
    tmux send-keys -t _todo:editor.1 ',t' C-m
    tmux send-keys -t _todo:editor.1 ':edit ~/Dropbox/todo/work.md' C-m
    tmux send-keys -t _todo:editor.1 ',t' C-m
    tmux send-keys -t _todo:editor.1 ':edit ~/Dropbox/todo/home.md' C-m
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux attach -t _todo
else
    tmux switch -t _todo
fi

# select 'editor' window
tmux select-window -t _todo:editor
tmux select-pane -t _todo:editor.0
