#!/bin/bash

# if 'knowledge' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: vim
#   - docsify: docsify serve

tmux has-session -t knowledge

if [ $? != 0 ]
then
    # editor window
    tmux new -s knowledge -n editor -d
    tmux send-keys -t knowledge:editor 'cd ~/knowledge-base' C-m
    tmux send-keys -t knowledge:editor 'vim .' C-m

    # docsify window
    tmux new-window -t knowledge -n docsify
    tmux send-keys -t knowledge:docsify 'cd ~/knowledge-base' C-m
    tmux send-keys -t knowledge:docsify 'docsify serve .' C-m
fi

# select window 'editor'
tmux select-window -t knowledge:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t knowledge
else
    tmux attach -t knowledge
fi
