#!/bin/bash

# if 'listings' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - make/test: make run-local + go test

tmux has-session -t listings

if [ $? != 0 ]
then
    # editor window
    tmux new -s listings -n editor -d
    tmux send-keys -t listings:editor 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-listings' C-m
    tmux send-keys -t listings:editor 'git pull' C-m
    tmux send-keys -t listings:editor 'vim .'

    # make/test window
    tmux new-window -t listings -n make/test
    tmux send-keys -t listings:make/test 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-listings' C-m
    tmux send-keys -t listings:make/test 'glide install' C-m
    tmux send-keys -t listings:make/test 'onchange -i -k "**/*.go" -- make run-local'
    tmux split-window -t listings:make/test
    tmux send-keys -t listings:make/test.1 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-listings' C-m
    tmux send-keys -t listings:make/test.1 'go test ./...'
fi

# select 'editor' pane
tmux select-pane -t listings:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t listings
else
    tmux attach -t listings
fi
