#!/bin/bash

# if 'zettelkasten' session exists, attach to it.
# otherwise, create it

tmux has-session -t zettelkasten

if [ $? != 0 ]
then
    tmux new -s zettelkasten -n editor -d
    tmux send-keys -t zettelkasten:editor 'cd ~/Projects/Personales/zettelkasten' C-m
    tmux send-keys -t zettelkasten:editor 'vim .' C-m
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux attach -t zettelkasten
else
    tmux switch -t zettelkasten
fi

# select window 'editor'
tmux select-window -t zettelkasten:editor
