#!/bin/bash

# if 'assetinfo' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - make/test: make run-local + go test

tmux has-session -t assetinfo

if [ $? != 0 ]
then
    # editor window
    tmux new -s assetinfo -n editor -d
    tmux send-keys -t assetinfo:editor 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-asset-info' C-m
    tmux send-keys -t assetinfo:editor 'git pull' C-m
    tmux send-keys -t assetinfo:editor 'vim .'

    # make/test window
    tmux new-window -t assetinfo -n make/test
    tmux send-keys -t assetinfo:make/test 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-asset-info' C-m
    tmux send-keys -t assetinfo:make/test 'glide install' C-m
    tmux send-keys -t assetinfo:make/test 'onchange -i -k "**/*.go" -- make run-local'
    tmux split-window -t assetinfo:make/test
    tmux send-keys -t assetinfo:make/test.1 'cd $GOPATH/src/github.com/foxbroadcasting/cpe-asset-info' C-m
    tmux send-keys -t assetinfo:make/test.1 'go test ./...'
fi

# select 'editor' pane
tmux select-pane -t assetinfo:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t assetinfo
else
    tmux attach -t assetinfo
fi
