#!/bin/bash

# if 'finance' session exists, attach to it.
# otherwise, create it

tmux has-session -t finance

if [ $? != 0 ]
then
    tmux new -s finance -n editor -d
    tmux send-keys -t finance:editor 'cd ~/Projects/Personales/personal_finance' C-m
    tmux send-keys -t finance:editor 'nvim .'
fi

# attach to session
# The TMUX environment variable will tell you if the current process is running
# under tmux or not (and whether to attach to tmux or just switch session)
if [ -z "$TMUX" ]; then
    tmux attach -t finance
else
    tmux switch -t finance
fi

# select window 'editor'
tmux select-window -t finance:editor
