#!/bin/bash

# open my 'hotlist' of websites in the browser

HOTLIST='https://www.toodledo.com/tasks/index.php#Main
https://x-team.slack.com/messages/C3N9KTFU5/
https://foxdcg.slack.com/messages/D3M4E6GDB/
https://mail.google.com/
https://mail.google.com/mail/u/?authuser=alexis.hevia@x-team.com
https://calendar.google.com/calendar/r
https://web.whatsapp.com/
https://feedly.com/i/my'

for url in $HOTLIST; do
  xdg-open $url
done
