#!/bin/bash

# if 'fox' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - tail: docker-compose up
# - test: bin/unit-test
# - vpn/flow: foxvpn and flow server

tmux has-session -t fox

if [ $? != 0 ]
then
    # editor window
    tmux new -s fox -n editor -d
    tmux send-keys -t fox:editor 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:editor 'nvm use' C-m
    tmux send-keys -t fox:editor 'source ../.aws_keys' C-m
    tmux send-keys -t fox:editor 'clear' C-m
    tmux send-keys -t fox:editor 'git pull' C-m
    tmux send-keys -t fox:editor 'vim .'

    # tail window
    tmux new-window -t fox -n tail
    tmux send-keys -t fox:tail 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:tail 'nvm use' C-m
    tmux send-keys -t fox:tail 'source ../.aws_keys' C-m
    tmux send-keys -t fox:tail 'clear' C-m
    tmux send-keys -t fox:tail 'ln -sf ./env/d2c/local.env .env' C-m
    tmux send-keys -t fox:tail 'bin/setup && bin/build && docker-compose up -d && docker-compose stop e2e && docker-compose stop e2e_base && docker-compose logs -f | grep -v health'

    # test window
    tmux new-window -t fox -n test
    tmux send-keys -t fox:test 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:test 'nvm use' C-m
    tmux send-keys -t fox:test 'source ../.aws_keys' C-m
    tmux send-keys -t fox:test 'clear' C-m
    tmux send-keys -t fox:test 'bin/unit-test -p service-video -P'

    # vpn/flow window
    tmux new-window -t fox -n vpn/flow
    tmux send-keys -t fox:vpn/flow 'foxvpn' C-m
    tmux split-window -t fox:vpn/flow
    tmux send-keys -t fox:vpn/flow.1 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:vpn/flow.1 'ctags -R packages' C-m
    tmux send-keys -t fox:vpn/flow.1 'bin/flow' C-m
fi

# select 'flow' pane
tmux select-pane -t fox:vpn/flow.0

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t fox
else
    tmux attach -t fox
fi
