#!/bin/bash

# if 'mdo-native' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - server: expo server

tmux has-session -t mdo-native

if [ $? != 0 ]
then
    # editor window
    tmux new -s mdo-native -n editor -d
    tmux send-keys -t mdo-native:editor 'cd $HOME/Projects/Personales/mdo-native' C-m
    tmux send-keys -t mdo-native:editor 'nvm use' C-m
    tmux send-keys -t mdo-native:editor 'git pull' C-m
    tmux send-keys -t mdo-native:editor 'vim .'

    # server window
    tmux new-window -t mdo-native -n server
    tmux send-keys -t mdo-native:server 'android-studio &' C-m
    tmux send-keys -t mdo-native:server 'cd $HOME/Projects/Personales/mdo-native' C-m
    tmux send-keys -t mdo-native:server 'nvm use' C-m
    tmux send-keys -t mdo-native:server 'npm install && npm start' C-m
fi

# select 'editor' pane
tmux select-pane -t mdo-native:editor

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t mdo-native
else
    tmux attach -t mdo-native
fi
