#!/bin/bash

# if 'clients' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor: vim

tmux has-session -t clients

if [ $? != 0 ]
then
    # editor window
    tmux new -s clients -n editor -d
    tmux send-keys -t clients:editor 'cd ~/Dropbox/clients' C-m
    tmux send-keys -t clients:editor 'source ./env_vars.sh' C-m
    tmux send-keys -t clients:editor 'vim .' C-m
    tmux send-keys -t clients:editor ',t' C-m
    tmux send-keys -t clients:editor ':edit ~/Dropbox/clients/worklog.md' C-m
fi

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t clients
else
    tmux attach -t clients
fi
