#!/bin/bash

# if 'todo' session exists, attach to it.
# otherwise, create it with the following windows:
#   - editor

tmux has-session -t todo

if [ $? != 0 ]
then
    # editor window
    tmux new -s todo -n editor -d
    tmux send-keys -t todo:editor 'cd ~/Dropbox' C-m
    tmux send-keys -t todo:editor 'vim .' C-m
    tmux send-keys -t todo:editor ',t' C-m
    tmux send-keys -t todo:editor ':edit ~/Dropbox/todo/todo.md' C-m
fi

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t todo
else
    tmux attach -t todo
fi
