#!/bin/bash

# if 'fox' session exists, attach to it.
# otherwise, create it with the following windows:
# - editor: vim
# - tail: docker-compose up
# - vpn/test: foxvpn and bin/unit-test

tmux has-session -t fox

if [ $? != 0 ]
then
    # editor window
    tmux new -s fox -n editor -d
    tmux send-keys -t fox:editor 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:editor 'nvm use' C-m
    tmux send-keys -t fox:editor 'source ../.aws_keys' C-m
    tmux send-keys -t fox:editor 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:editor 'clear' C-m
    tmux send-keys -t fox:editor 'git pull' C-m
    tmux send-keys -t fox:editor 'vim .'

    # tail window
    tmux new-window -t fox -n tail
    tmux send-keys -t fox:tail 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:tail 'nvm use' C-m
    tmux send-keys -t fox:tail 'source ../.aws_keys' C-m
    tmux send-keys -t fox:tail 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:tail 'clear' C-m
    tmux send-keys -t fox:tail 'ln -sf ./env/d2c/local.env .env' C-m
    tmux send-keys -t fox:tail 'bin/setup && bin/build && docker-compose up -d && docker-compose logs -f | grep -v health'

    # vpn/test window
    tmux new-window -t fox -n vpn/test
    tmux send-keys -t fox:vpn/test 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:vpn/test 'foxvpn' C-m
    tmux split-window -t fox:vpn/test
    tmux send-keys -t fox:vpn/test.1 'cd $HOME/Projects/FOX/dcgapi-services' C-m
    tmux send-keys -t fox:vpn/test.1 'nvm use' C-m
    tmux send-keys -t fox:vpn/test.1 'source ../.aws_keys' C-m
    tmux send-keys -t fox:vpn/test.1 'source $HOME/Dropbox/env_vars.sh' C-m
    tmux send-keys -t fox:vpn/test.1 'clear' C-m
    tmux send-keys -t fox:vpn/test.1 'bin/unit-test -p service-video -P'
fi

# select 'vpn' pane
tmux select-pane -t fox:vpn/test.0

# attach to session
tmux ls | grep attached
if [ $? == 0 ]; then
    tmux switch -t fox
else
    tmux attach -t fox
fi
